services:
  app:
    build:
      context: .
    container_name: app-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh container-mysql:3306 -- npx prisma db push && npx tsx watch src/server.ts"]

  mysql:
    container_name: container-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha-mysql
      MYSQL_DATABASE: Gateway
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
